### ISSUE TITLE
exception when switching to pygments from sublime highlighter

### ISSUE THREAD

**Issue by rwols** [facelessuser/sublime-markdown-popups#110]
I don't have time to dig into this but when I set `"mdpopups.use_sublime_highlighter": false,` in my Packages/User/Preferences.sublime-settings the following happens:

```
Traceback (most recent call last):
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/hover.py", line 148, in <lambda>
    if contents:
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/hover.py", line 151, in _show_hover
    _test_contents.clear()
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/hover.py", line 145, in hover_content
    
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/views.py", line 451, in minihtml
    return mdpopups.md2html(view, mdpopups.format_frontmatter(frontmatter) + result)
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 439, in md2html
    ).convert(_markup_template(markup, template_vars, template_env_options)).replace('&quot;', '"')
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3/markdown/core.py", line 265, in convert
    self.lines = prep.run(self.lines)
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/pymdownx/st3/pymdownx/superfences.py", line 737, in run
    return self.search_nested(lines)
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/pymdownx/st3/pymdownx/superfences.py", line 601, in search_nested
    self.eval_fence(ws, content, start, end)
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/pymdownx/st3/pymdownx/superfences.py", line 407, in eval_fence
    self.process_nested_block(ws, content, start, end)
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/pymdownx/st3/pymdownx/superfences.py", line 451, in process_nested_block
    code = entry["formatter"](self.rebuild_block(self.code), self.lang, self.options, self.md)
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/pymdownx/st3/pymdownx/superfences.py", line 666, in highlight
    linespecial=linespecial
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/mdx/highlight.py", line 450, in highlight
    code = highlight(src, lexer, formatter)
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/pygments/all/pygments/__init__.py", line 87, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/pygments/all/pygments/__init__.py", line 66, in format
    formatter.format(tokens, realoutfile)
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/pygments/all/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/pygments/all/pygments/formatters/html.py", line 831, in format_unencoded
    source = self.wrap(source, outfile)
  File "/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/mdx/highlight.py", line 281, in wrap
    return self._wrap_code(self, source)
TypeError: _wrap_code() takes 2 positional arguments but 3 were given
```

**Comment by facelessuser** [comment]
So do you have a need for pygments? Because I've been considering killing it off.

**Comment by rwols** [comment]
Yes. The markdown code blocks from language servers are not reliably tokenizable by a .sublime-syntax unfortunately.

**Comment by rwols** [comment]
For instance pyright may return

```
(class) Foo
```

if you hover of a class named Foo. This is not actually tokenizable by Python.sublime-syntax and results in some invalid.illegal scopes.

**Comment by facelessuser** [comment]
Are they reliable in pygments? I know some languages fair better than others in pygments. I don't mind fixing issues, it was more a question of curiosity.

**Comment by rwols** [comment]
pygments seems to be more forgiving about invalid tokens. It doesn't get much right I'll give you that.

I wonder whether mdpopups can figure out what "forgiving" context to use in a .sublime-syntax.

**Comment by rwols** [comment]
See also the discussion in https://github.com/microsoft/language-server-protocol/issues/1115

**Comment by dmilith** [comment]
Well, I applied that patch on my local version, but the issue still persists?

**Comment by dmilith** [comment]
You also have to patch same return statement on line 281 for pygments to work.

**Comment by facelessuser** [comment]
Yup 281 needs patching too, I'll have that in the next release
