### ISSUE TITLE
`ImportError: No module named 'yaml'` in OSX High Sierra

### ISSUE THREAD

**Issue by cbortz** [facelessuser/sublime-markdown-popups#54]
Hey y'all!

I recently performed a clean reformat of my OSX system with High Sierra. After installing sublime, I installed the [Material Theme](https://github.com/equinusocio/material-theme) package, which has markdown-popups as a dependency. I noticed that after installing I wasn't able to activate the Material Theme at all through the GUI.

So, what does this have to do with markdown popups? Checking the console, I found this:

```bash
reloading plugin Material Theme.MT
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "MT in /Users/cbortz/Library/Application Support/Sublime Text 3/Installed Packages/Material Theme.sublime-package", line 1, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "utils in /Users/cbortz/Library/Application Support/Sublime Text 3/Installed Packages/Material Theme.sublime-package", line 3, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "utils.config in /Users/cbortz/Library/Application Support/Sublime Text 3/Installed Packages/Material Theme.sublime-package", line 8, in <module>
  File "/Users/cbortz/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/__init__.py", line 27, in <module>
    from . import frontmatter
  File "/Users/cbortz/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3/mdpopups/frontmatter.py", line 2, in <module>
    import yaml
ImportError: No module named 'yaml'
```

The last couple of lines there seem to point to mdpopups trying to import yaml. So, I did the following to install PyYaml...

```
$ sudo easy_install pip
$ sudo pip install pyyaml
```

Since then I've confirmed that I can `import yaml` from a python console. Any thoughts? Is there some configuration for setting a proper python path when launching SublimeText?

**Comment by facelessuser** [comment]
There was some Pacakge Control issues recently, but they have been resolved.  You cannot pip install into Sublime, Package Control should install dependencies for you.  I'd check with the Material theme if they are requiring dependencies properly, and if not, they should fix it upstream.  If they are, you can take it up with Package Control and get some guidance there.
