### ISSUE TITLE
Error mdpopups: Failed to convert/retrieve scheme to CSS!

### ISSUE THREAD

**Issue by OdinTech3** [facelessuser/sublime-markdown-popups#65]
I keep on getting this error message:

`mdpopups: Failed to convert/retrieve scheme to CSS!`

logged to the console whenever I hover over a symbol on my code base. It occurs irrespective of the language server I am using. I have seen it logged while using the pyls and rlang language server

I am using:

* MacOS 10.13.6
* Sublime Text Build 3184 (Dev Channel)
* LSP v0.7.3 installed using Package Control

I started this issue on the github issue page for [tomv564/LSP](https://github.com/tomv564/LSP/issues/487), which I advise you look through.

I found out that changing the `DEFAULT_CSS` path from ___'Packages/mdpopups/css/default.css'___ to ___'Packages/mdpopups/default.css'___ and then subsequently making a copy of the default.css file to the root of the mdpopups directory fixed the problem.

Do you guys think that `sublime.load_resource` method that was used to get the css file can not load nested directories?

**Comment by facelessuser** [comment]
Post what color scheme to are using please.

**Comment by OdinTech3** [comment]
I am using the ayu-mirage theme `Packages/ayu/ayu-mirage.tmTheme` provided by the [ayu sublime theme](https://packagecontrol.io/packages/ayu)

**Comment by facelessuser** [comment]
There are some newer scheme features that I am in the process of writing support code for. I'm doubtful there is a CSS load issue, but I'll look into this when I get a chance. Hopefully soon as it is in my list.

**Comment by OdinTech3** [comment]
Alright thanks for getting back to me so quickly, if you need me to help you in some way then don't hesitate to ask.

**Comment by facelessuser** [comment]
ayu is using old school tmTheme files, so no issues with the new scheme features.

I am not seeing the CSS load issue though either.  Mine loads the CSS from its location which is `Packages/mdpopups/css/default.css`.

I'll try and dig a bit more, but so far it is looking like you are having an issue specific to your unique installation.

**Comment by facelessuser** [comment]
Can you run the following command from your Sublime terminal?

```py
sublime.load_resource('Packages/mdpopups/css/default.css')
```

This is what I get:

```py
>>> sublime.load_resource('Packages/mdpopups/css/default.css')
'{%- if var.default_style %}\nhtml {\n  --mdpopups-font-mono: "sf mono", Consolas, "Liberation Mono", Menlo, Courier, monospace;\n  {%- if var.sublime_version < 3127 %}\n  --mdpopups-admon-fg: var(--background);\n  --mdpopups-admon-info-fg: var(--background);\n  --mdpopups-admon-error-fg: var(--background);\n  --mdpopups-admon-warning-fg: var(--background);\n  --mdpopups-admon-success-fg: var(--background);\n  --mdpopups-admon-bg: color(var(--background) blend(var(--foreground) 30%));\n  --mdpopups-admon-info-bg: color(var(--background) blend(var(--bluish) 30%));\n  --mdpopups-admon-error-bg: color(var(--background) blend(var(--redish) 30%));\n  --mdpopups-admon-warning-bg: color(var(--background) blend(var(--orangish) 30%));\n  --mdpopups-admon-success-bg: color(var(--background) blend(var(--greenish) 30%));\n  {%- else %}\n  --mdpopups-admon-fg: var(--foreground);\n  --mdpopups-admon-info-fg: var(--foreground);\n  --mdpopups-admon-error-fg: var(--foreground);\n  --mdpopups-admon-warning-fg: var(--foreground);\n  --mdpopups-admon-success-fg: var(--foreground);\n  --mdpopups-admon-bg: var(--background);\n  --mdpopups-admon-info-bg: var(--background);\n  --mdpopups-admon-error-bg: var(--background);\n  --mdpopups-admon-warning-bg: var(--background);\n  --mdpopups-admon-success-bg: var(--background);\n  {%- endif %}\n  --mdpopups-admon-accent: color(var(--background) blend(var(--foreground) 50%));\n  --mdpopups-admon-title-fg:  var(--foreground);\n  --mdpopups-admon-info-title-fg:  var(--foreground);\n  --mdpopups-admon-error-title-fg:  var(--foreground);\n  --mdpopups-admon-warning-title-fg:  var(--foreground);\n  --mdpopups-admon-success-title-fg:  var(--foreground);\n  --mdpopups-admon-info-accent: color(var(--background) blend(var(--bluish) 50%));\n  --mdpopups-admon-error-accent: color(var(--background) blend(var(--redish) 50%));\n  --mdpopups-admon-warning-accent: color(var(--background) blend(var(--orangish) 50%));\n  --mdpopups-admon-success-accent: color(var(--background) blend(var(--greenish) 50%));\n  --mdpopups-kbd-fg: var(--background);\n  --mdpopups-kbd-bg: var(--foreground);\n}\nhtml.light {\n  --mdpopups-hr: color(var(--foreground) blend(white 80%));\n  --mdpopups-kbd-border: color(var(--foreground) blend(white 80%));\n  --mdpopups-hl-border: color(var(--background) blend(black 90%));\n  --mdpopups-hl-bg: color(var(--background) blend(black 98%));\n}\nhtml.dark {\n  --mdpopups-hr: color(var(--foreground) blend(black 80%));\n  --mdpopups-kbd-border: color(var(--foreground) blend(black 80%));\n  --mdpopups-hl-border: color(var(--background) blend(white 90%));\n{%- if var.sublime_version < 3127 %}\n  /* 3127 borders allow us more flexibility with code backgrounds. Older versions are going to stick to darkening. */\n  --mdpopups-hl-bg: color(var(--background) blend(black 98%));\n{%- else %}\n  --mdpopups-hl-bg: color(var(--background) blend(white 98%));\n{%- endif %}\n}\nhtml, body { padding: 0; margin: 0; }\ndiv.mdpopups {\n  display: block;\n  margin: 0;\n  padding: 0;\n  font-size: 1rem;\n  line-height: 1.1rem;\n}\n.mdpopups .highlight,\n.mdpopups code,\n.mdpopups var,\n.mdpopups tt {\n  font-family: var(--mdpopups-font-mono);\n}\n.mdpopups div { display: block; }\n/* Headers */\n.mdpopups h1 { font-size: 1.5rem; }\n.mdpopups h2 { font-size: 1.4rem; }\n.mdpopups h3 { font-size: 1.3rem; }\n.mdpopups h4 { font-size: 1.2rem; }\n.mdpopups h5 { font-size: 1.1rem; }\n.mdpopups h6 { font-size: 1rem; }\n.mdpopups h1, .mdpopups h2, .mdpopups h3, .mdpopups h4, .mdpopups h5, .mdpopups h6 {\n  margin-top: 0.2rem;\n  margin-bottom: 0.2rem;\n}\n/* Blockquote support. */\n.mdpopups blockquote { display: block; font-style: italic; }\n/* Horizontal rule support. */\n.mdpopups hr {\n  display: block;\n  {%- if var.sublime_version < 3127 %}\n  padding: 1px;\n  background-color: var(--mdpopups-hr);\n  {%- else %}\n  border-color: var(--mdpopups-hr);\n  border-style: solid;\n  border-width: 0 0 1px 0;\n  {%- endif %}\n  margin-top: 1rem;\n  margin-bottom: 1rem;\n}\n/* Description list support */\n.mdpopups dl { display: block; }\n.mdpopups dt {\n  display: block;\n  font-style: italic;\n  font-weight: bold;\n  margin-bottom: 0.5rem;\n}\n.mdpopups dd {\n  display: block;\n  margin-left: 1.5rem;\n  margin-bottom: 0.5rem;\n}\n/* Preformatted block */\n.mdpopups pre { display: block; }\n/* Blocks */\n.mdpopups blockquote, .mdpopups ol, .mdpopups ul, .mdpopups dl, .mdpopups p {\n  padding: 0;\n  margin-top: 0;\n  margin-bottom: 0.5rem;\n  margin-left: 0;\n  margin-right: 0;\n}\n.mdpopups ul, .mdpopups ol { padding-left: 2rem; }\n/* kbd */\n.mdpopups kbd {\n  display: inline;\n  font-size: 0.9rem;\n  padding: 0.05rem 0.25rem;\n  border-radius: 0.25rem;\n  background-color: var(--mdpopups-kbd-bg);\n  color: var(--mdpopups-kbd-fg);\n  border: 1px solid var(--mdpopups-kbd-border);\n}\n/* Admontions/Panels */\n.mdpopups .admonition {\n  display: block;\n  padding: 0 0.5rem 0.5rem 0.5rem;\n  border-radius: 0.25rem;\n  margin-bottom: 0.5rem;\n  background-color: var(--mdpopups-admon-bg);\n  color: var(--mdpopups-admon-fg);\n  border: 1px solid var(--mdpopups-admon-accent);\n}\n.mdpopups .admonition-title {\n  font-weight: 600;\n  font-size: 1.1rem;\n  margin: 0 -0.5rem 0.5rem -0.5rem;\n  padding: 0.1rem 0.5rem 0.1rem 0.5rem;\n  border-top-left-radius: 0.25rem;\n  border-top-right-radius: 0.25rem;\n  color:  var(--mdpopups-admon-title-fg);\n  background-color: var(--mdpopups-admon-accent);\n}\n/* Colorized Admonitions classes. */\n.mdpopups .admonition.panel-success .admonition-title {\n  color: var(--mdpopups-admon-success-title-fg);\n  background-color: var(--mdpopups-admon-success-accent);\n}\n.mdpopups .admonition.panel-success {\n  color:  var(--mdpopups-admon-success-fg);\n  background-color: var(--mdpopups-admon-success-bg);\n  border-color: var(--mdpopups-admon-success-accent);\n}\n.mdpopups .admonition.panel-warning .admonition-title {\n  color: var(--mdpopups-admon-warning-title-fg);\n  background-color: var(--mdpopups-admon-warning-accent);\n}\n.mdpopups .admonition.panel-warning {\n  color:  var(--mdpopups-admon-warning-fg);\n  background-color: var(--mdpopups-admon-warning-bg);\n  border-color: var(--mdpopups-admon-warning-accent);\n}\n.mdpopups .admonition.panel-error .admonition-title {\n  color: var(--mdpopups-admon-error-title-fg);\n  background-color: var(--mdpopups-admon-error-accent);\n}\n.mdpopups .admonition.panel-error {\n  color:  var(--mdpopups-admon-error-fg);\n  background-color: var(--mdpopups-admon-error-bg);\n  border-color: var(--mdpopups-admon-error-accent);\n}\n.mdpopups .admonition.panel-info .admonition-title {\n  color: var(--mdpopups-admon-info-title-fg);\n  background-color: var(--mdpopups-admon-info-accent);\n}\n.mdpopups .admonition.panel-info {\n  color:  var(--mdpopups-admon-info-fg);\n  background-color: var(--mdpopups-admon-info-bg);\n  border-color: var(--mdpopups-admon-info-accent);\n}\n.mdpopups .highlight {\n  border: 1px solid var(--mdpopups-hl-border);\n  border-radius: 0.25rem;\n  font-size: 0.9rem;\n  {%- if not var.use_pygments %}\n  background-color: var(--mdpopups-hl-bg);\n  {%- endif %}\n}\n.mdpopups div.highlight,\n.mdpopups pre.highlight {\n  padding: 0.5rem;\n  margin-bottom: 0.5rem;\n  font-size: 1rem;\n}\n.mdpopups code.highlight{\n  padding: 0.05rem 0.25rem;\n}\n{%- endif %}\n'
```

**Comment by OdinTech3** [comment]
This is the output I get
```
>>> sublime.load_resource('Packages/mdpopups/css/default.css')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
```

**Comment by facelessuser** [comment]
Hmm, and you have `Packages/mdpopups/css/default.css` at the proper location with no modifications to it?

I'm just not seeing this issue.  It may be possible that something with Sublime is corrupted and its `load_resource` is failing when it shouldn't. If the file is there, then it should be found. You may need to try it on a clean Sublime install.

**Comment by OdinTech3** [comment]
Alright then, I'll give it a try and get back to you

**Comment by bordaigorl** [comment]
I get the same error.
This is what I get from `sublime.find_resources`:

```python
>>> [x for x in sublime.find_resources("*") if "mdpopup" in x]
['Packages/0_package_control_loader/55-mdpopups.py', 'Packages/mdpopups/.DS_Store', 'Packages/mdpopups/.gitignore', 'Packages/mdpopups/.spelling.yml', 'Packages/mdpopups/.travis.yml', 'Packages/mdpopups/dependency-metadata.json', 'Packages/mdpopups/LICENSE', 'Packages/mdpopups/mkdocs.yml', 'Packages/mdpopups/Preferences.sublime-settings', 'Packages/mdpopups/README.md', 'Packages/mdpopups/setup.cfg', 'Packages/mdpopups/docs/theme/extra-d04c85ed4a.css', 'Packages/mdpopups/docs/theme/extra-d8800ea088.js', 'Packages/mdpopups/st3/mdpopups/__init__.py', 'Packages/mdpopups/st3/mdpopups/colorbox.py', 'Packages/mdpopups/st3/mdpopups/frontmatter.py', 'Packages/mdpopups/st3/mdpopups/imagetint.py', 'Packages/mdpopups/st3/mdpopups/png.py', 'Packages/mdpopups/st3/mdpopups/rgba.py', 'Packages/mdpopups/st3/mdpopups/st_clean_css.py', 'Packages/mdpopups/st3/mdpopups/st_code_highlight.py', 'Packages/mdpopups/st3/mdpopups/st_color_scheme_matcher.py', 'Packages/mdpopups/st3/mdpopups/st_mapping.py', 'Packages/mdpopups/st3/mdpopups/st_pygments_highlight.py', 'Packages/mdpopups/st3/mdpopups/st_scheme_template.py', 'Packages/mdpopups/st3/mdpopups/version.py', 'Packages/mdpopups/st3/mdpopups/x11colors.py', 'Packages/mdpopups/st3/mdpopups/file_strip/__init__.py', 'Packages/mdpopups/st3/mdpopups/file_strip/comments.py', 'Packages/mdpopups/st3/mdpopups/file_strip/json.py', 'Packages/mdpopups/st3/mdpopups/mdx/__init__.py', 'Packages/mdpopups/st3/mdpopups/mdx/highlight.py', 'Packages/mdpopups/st3/mdpopups/mdx/inlinehilite.py', 'Packages/mdpopups/st3/mdpopups/mdx/superfences.py', 'Packages/mdpopups/tests/__init__.py', 'Packages/mdpopups/tests/spellcheck.py', 'Packages/mdpopups/tests/test_json.py', 'Packages/mdpopups/tests/validate_json_format.py']
```

For some reason it does not find `css/default.css`.
I tried to open it using `ResourceViewer` and it's there.

**Comment by facelessuser** [comment]
@bordaigorl , I would need you to specifically do this and give me the output: `sublime.load_resource('Packages/mdpopups/css/default.css')`.  This is more what I'm interested in, as I believe this is what we are doing internally.

**Comment by OdinTech3** [comment]
This is the output from running the command

```
>>> sublime.load_resource('Packages/mdpopups/css/default.css')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
```
I am running Build 3205, MacOSX 10.13.6

**Comment by facelessuser** [comment]
Very curious. If you were create a new file with unique name in the css folder, can it find that?

**Comment by bordaigorl** [comment]
@facelessuser 

>  I would need you to specifically do this and give me the output

Yes sorry I should have mentioned that I did try that, getting the same result as @OdinTech3

**Comment by OdinTech3** [comment]
I tried creating a new file `unique_default_copy.txt` in the same folder, it still cant find it

```
>>> sublime.load_resource('Packages/mdpopups/css/unique_default_copy.txt')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
```

**Comment by facelessuser** [comment]
That's weird.  I was hoping that the maybe the other file was somehow corrupted in a cache.  It's odd that it can't fine any file in that folder.

**Comment by facelessuser** [comment]
I would check file permissions on the folder and the file as well.  Maybe something weird there? I'm talking with some other Sublime developers, even wbond about this weird issue.

**Comment by facelessuser** [comment]
@bordaigorl, what OS are you using? Curious if it is the same as @OdinTech3.

**Comment by wbond** [comment]
Can you post the output of the following commands?

```bash
ls -la "$HOME/Library/Application Support/Sublime Text 3/Packages/mdpopups/"
ls -la "$HOME/Library/Application Support/Sublime Text 3/Packages/mdpopups/css/"
ls -la "$HOME/Library/Application Support/Sublime Text 3/Installed Packages/"
```

**Comment by OdinTech3** [comment]
```
❯ ls -la "$HOME/Library/Application Support/Sublime Text 3/Packages/mdpopups/"
  
total 112
drwxr-xr-x  17 nickmuoh  staff   544 Jan 24 09:56 .
drwx------  37 nickmuoh  staff  1184 Apr  5 13:55 ..
-rw-r--r--@  1 nickmuoh  staff  8196 Apr  5 13:52 .DS_Store
-rw-r--r--   1 nickmuoh  staff   735 Jan 16 05:24 .gitignore
-rw-r--r--   1 nickmuoh  staff  1333 Jan 16 05:24 .spelling.yml
-rw-r--r--   1 nickmuoh  staff  1107 Jan 16 05:24 .travis.yml
-rw-r--r--   1 nickmuoh  staff  1084 Jan 16 05:24 LICENSE
-rw-r--r--   1 nickmuoh  staff  2020 Jan 16 05:24 Preferences.sublime-settings
-rw-r--r--   1 nickmuoh  staff  3030 Jan 16 05:24 README.md
drwxr-xr-x   5 nickmuoh  staff   160 Apr  5 13:56 css
-rw-r--r--   1 nickmuoh  staff  7148 Jan 16 05:24 default.css
-rw-r--r--   1 nickmuoh  staff   185 Jan 16 05:24 dependency-metadata.json
drwxr-xr-x   4 nickmuoh  staff   128 Dec  9  2017 docs
-rw-r--r--   1 nickmuoh  staff  3094 Jan 16 05:24 mkdocs.yml
-rw-r--r--   1 nickmuoh  staff   104 Jan 16 05:24 setup.cfg
drwxr-xr-x   3 nickmuoh  staff    96 Jan 16 05:24 st3
drwxr-xr-x   6 nickmuoh  staff   192 Dec  9  2017 tests
```

---

```
❯ ls -la "$HOME/Library/Application Support/Sublime Text 3/Packages/mdpopups/css/"
total 48
drwxr-xr-x   5 nickmuoh  staff   160 Apr  5 13:56 .
drwxr-xr-x  17 nickmuoh  staff   544 Jan 24 09:56 ..
-rw-r--r--@  1 nickmuoh  staff  6148 Apr  5 13:52 .DS_Store
-rw-r--r--   1 nickmuoh  staff  7148 Jan 16 05:24 default.css
-rw-r--r--   1 nickmuoh  staff  7148 Jan 16 05:24 unique_default_copy.txt
```

--

```
❯ ls -la "$HOME/Library/Application Support/Sublime Text 3/Installed Packages/"
total 34368
drwx------  61 nickmuoh  staff     1952 Apr  5 13:55 .
drwx------  11 nickmuoh  staff      352 Apr  4 08:59 ..
-rw-r--r--@  1 nickmuoh  staff     6148 Apr 28  2018 .DS_Store
-rw-r--r--   1 nickmuoh  staff     6284 Jan 24 10:36 0_package_control_loader.sublime-package
-rw-r--r--   1 nickmuoh  staff   665592 Apr  5 13:55 A File Icon.sublime-package
-rw-r--r--   1 nickmuoh  staff    23873 Jul 30  2018 Advanced CSV.sublime-package
-rw-r--r--   1 nickmuoh  staff     7229 Jan  7 16:17 ApacheConf.sublime-package
-rw-r--r--   1 nickmuoh  staff   390908 Aug 27  2018 AutoDocstring.sublime-package
-rw-r--r--   1 nickmuoh  staff     7154 Dec  9  2017 AutoFileName.sublime-package
-rw-r--r--   1 nickmuoh  staff   274106 Jan 18 07:30 BracketHighlighter.sublime-package
-rw-r--r--   1 nickmuoh  staff   249324 Aug 27  2018 CSS3.sublime-package
-rw-r--r--   1 nickmuoh  staff   196946 Dec 21 04:57 Color Highlight.sublime-package
-rw-r--r--   1 nickmuoh  staff    12499 Dec  9  2017 DashDoc.sublime-package
-rw-r--r--   1 nickmuoh  staff    68932 Feb 23  2018 Djaneiro.sublime-package
-rw-r--r--   1 nickmuoh  staff    15517 May 22  2018 Django Manage Commands.sublime-package
-rw-r--r--   1 nickmuoh  staff    36356 Dec  9  2017 DocBlockr.sublime-package
-rw-r--r--   1 nickmuoh  staff   762596 Nov 23 00:42 DotENV.sublime-package
-rw-r--r--   1 nickmuoh  staff     6226 Aug 31  2018 EasySettings.sublime-package
-rw-r--r--   1 nickmuoh  staff  1474607 Aug 27  2018 Elm Language Support.sublime-package
-rw-r--r--   1 nickmuoh  staff   231150 Jun 28  2018 Emmet.sublime-package
-rw-r--r--   1 nickmuoh  staff     9761 Nov 23 00:39 Environment Settings.sublime-package
-rw-r--r--   1 nickmuoh  staff   983118 Jul 21  2018 FileManager.sublime-package
-rw-r--r--   1 nickmuoh  staff    29527 Dec  9  2017 Gist.sublime-package
-rw-r--r--   1 nickmuoh  staff     5557 Apr  2  2018 Git Config.sublime-package
-rw-r--r--   1 nickmuoh  staff   109799 Mar 15 18:02 GitGutter.sublime-package
-rw-r--r--   1 nickmuoh  staff   248863 Feb 21 14:22 GitSavvy.sublime-package
-rw-r--r--   1 nickmuoh  staff     5630 Mar 28  2018 Graql Syntax.sublime-package
-rw-r--r--   1 nickmuoh  staff   669971 Nov 25 04:25 Hermes.sublime-package
-rw-r--r--   1 nickmuoh  staff     2447 Apr  4 21:53 INI.sublime-package
-rw-r--r--   1 nickmuoh  staff    17763 Jan 30  2018 JavaScript & NodeJS Snippets.sublime-package
-rw-r--r--   1 nickmuoh  staff    12314 Dec  9  2017 Jinja2.sublime-package
-rw-r--r--   1 nickmuoh  staff   135842 Jan 22 02:30 JsFormat.sublime-package
-rw-r--r--   1 nickmuoh  staff   338533 Mar 20 18:06 LSP.sublime-package
-rw-r--r--   1 nickmuoh  staff   250251 Oct  6 07:53 MagicPython.sublime-package
-rw-r--r--   1 nickmuoh  staff    23740 Jul 28  2018 Markdown Extended.sublime-package
-rw-r--r--   1 nickmuoh  staff  1788633 Jan  3 05:35 MarkdownPreview.sublime-package
-rw-r--r--   1 nickmuoh  staff  3370318 Mar 18 22:19 Meetio.sublime-package
-rw-r--r--   1 nickmuoh  staff   286331 Dec  9  2017 Package Control.sublime-package
-rw-r--r--   1 nickmuoh  staff    22481 Mar 24  2018 PackageSync.sublime-package
-rw-r--r--   1 nickmuoh  staff     7330 Nov  6 14:00 PackagesUI.sublime-package
drwxr-xr-x   4 nickmuoh  staff      128 Dec  9  2017 PyV8
-rw-r--r--   1 nickmuoh  staff   312481 Mar  5 02:22 PypiPackageInfo.sublime-package
-rw-r--r--   1 nickmuoh  staff    92007 Dec  9  2017 Python Breakpoints.sublime-package
-rw-r--r--   1 nickmuoh  staff    11633 Mar 14 08:22 QuickSettings.sublime-package
-rw-r--r--   1 nickmuoh  staff    50967 Jan 22 02:30 Sass.sublime-package
-rw-r--r--   1 nickmuoh  staff    48852 Apr  2 21:12 Solarized Color Scheme.sublime-package
-rw-r--r--   1 nickmuoh  staff     7987 Jan 13 14:23 StatusBarSymbols.sublime-package
-rw-r--r--   1 nickmuoh  staff     4915 Feb  4 19:19 SublimeLinter-contrib-mypy.sublime-package
-rw-r--r--   1 nickmuoh  staff     6149 Oct 16 08:15 SublimeLinter-eslint.sublime-package
-rw-r--r--   1 nickmuoh  staff     5280 Dec  4 09:03 SublimeLinter-flake8.sublime-package
-rw-r--r--   1 nickmuoh  staff     4496 May 18  2018 SublimeLinter-jshint.sublime-package
-rw-r--r--   1 nickmuoh  staff     2945 Apr  1  2018 SublimeLinter-json.sublime-package
-rw-r--r--   1 nickmuoh  staff   137890 Mar 26 21:59 SublimeLinter.sublime-package
-rw-r--r--   1 nickmuoh  staff    10075 Nov  6 14:00 TOML.sublime-package
-rw-r--r--   1 nickmuoh  staff    10217 Apr 21  2018 View In Browser.sublime-package
-rw-r--r--   1 nickmuoh  staff    11848 Sep 24  2018 Virtualenv.sublime-package
-rw-r--r--   1 nickmuoh  staff   284777 Nov 23 01:04 Vue Syntax Highlight.sublime-package
-rw-r--r--   1 nickmuoh  staff  1706666 Mar 26 03:31 ayu.sublime-package
-rw-r--r--   1 nickmuoh  staff    54042 May 10  2018 nginx.sublime-package
-rw-r--r--   1 nickmuoh  staff    15680 Apr 21  2018 npm.sublime-package
-rw-r--r--   1 nickmuoh  staff    74080 Mar 30  2018 requirementstxt.sublime-package
```

**Comment by wbond** [comment]
Can you post the contents of your Sublime Text console after starting ST3 fresh?

**Comment by bordaigorl** [comment]
I am on MacOS 10.11.6 using ST 3200

**Comment by facelessuser** [comment]
Also, what happens when you drop the mdpopups folder into your sidebar, does the `css` folder show up properly in the project?

**Comment by OdinTech3** [comment]
Yeah it does: 

![Screen Shot 2019-04-05 at 4 50 19 PM](https://user-images.githubusercontent.com/14257815/55655731-ef34d600-57c2-11e9-8860-2e57e72d33db.png)

**Comment by facelessuser** [comment]
It sounded like from wbond that the same indexer is used for the sidebar, so we were hoping to see something odd, that would confirm that it is having a difficult time accessing the file, but no, that looks quite normal...

**Comment by bordaigorl** [comment]
> Also, what happens when you drop the mdpopups folder into your sidebar, does the `css` folder show up properly in the project?

@facelessuser yes it does

**Comment by facelessuser** [comment]
Here's some new info from jps:

```
4:27 PM] jps: Note that they'd need to add the entire Packages/ dir to the sidebar, not just the mdpopups folder - it's worth testing at least
[4:27 PM] jps: I think when the catalogue encounters a suspected duplicate folder, it will log a "foo has been seen before" message to the console
[4:29 PM] jps: Internally, the catalogue does keep track of most information that stat would report (size+write time+flags), and it also emits fine grained change notifications on the C++ side of things, but neither is currently exposed to the API
```

Can we attempt to add the full Packages directory to the sidebar, and see what happens?

**Comment by bordaigorl** [comment]
@facelessuser if I drop the entire Packages folder I still can navigate to `mdpopups/css/default.css`

**Comment by OdinTech3** [comment]
> Here's some new info from jps:
> 
> ```
> 4:27 PM] jps: Note that they'd need to add the entire Packages/ dir to the sidebar, not just the mdpopups folder - it's worth testing at least
> [4:27 PM] jps: I think when the catalogue encounters a suspected duplicate folder, it will log a "foo has been seen before" message to the console
> [4:29 PM] jps: Internally, the catalogue does keep track of most information that stat would report (size+write time+flags), and it also emits fine grained change notifications on the C++ side of things, but neither is currently exposed to the API
> ```
> Can we attempt to add the full Packages directory to the sidebar, and see what happens?

What is jps?

**Comment by facelessuser** [comment]
The author of Sublime Text.

**Comment by mheinzler** [comment]
I had the exact same issue for some time now and finally found the reason for this. After installing the CSS3 package, I disabled the standard CSS package as recommened.

As soon as I enabled it again, `load_resource` could find all the files in the `css` folder immediately.

**Comment by wbond** [comment]
> As soon as I enabled it again, load_resource could find all the files in the css folder immediately.

It would be great to have an issue filed for this at https://github.com/SublimeTextIssues/Core/issues!

**Comment by facelessuser** [comment]
@mheinzler, thank you for this info! This is what I suspected (not that specific package, but something like this), but I hadn't yet been able to prove it.

@wbond , I will try and get an issue created within the next day or so.

**Comment by facelessuser** [comment]
I'm considering changing the name of our CSS folder. It looks as if Sublime isn't going to get to fixing this anytime soon.

**Comment by wbond** [comment]
At the very least the bug will be present for every release of ST3, so that is probably a good call.

**Comment by facelessuser** [comment]
lol, that was fast responding @wbond :slightly_smiling_face:.

**Comment by facelessuser** [comment]
This should be fixed via https://github.com/facelessuser/sublime-markdown-popups/commit/f0a52003383344679744515babdc76063ce38d84
